spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
