spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=user
spring.datasource.password=password

cors.allowed.origins=http://localhost:5173

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=thisisaverysecuresecretkeywithmorethan32chars123
jwt.expiration=86400000

spring.profiles.active=local

app.2fa.enabled=true
app.2fa.delivery=twilio
app.mail.from=noreply@attendance.local

twilio.account-sid=
twilio.api-key-sid=
twilio.api-key-secret=
twilio.verify-service-sid=